#### 1: Importing the numpy package under the name `np`

In [65]:
import numpy as np


#### 2: Printing the numpy version and the configuration (★☆☆)

In [66]:
print(np.__version__)
print(np.show_config())


1.26.2
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30152",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.5",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30152",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86",
      "family": "x86",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86",
      "family": "x86",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "auto"
    },
    "lapack": {
      "name": "dep78953104",
      "found": true,
      "version": "1.26.2",
      "detection method": "internal",
      "include directory": "unknown",
      "lib directory": "unknown",
      "openblas configuration": "unknown",
      "pc file directory":

#### 3: Creating a null vector of size 10 (★☆☆)

In [67]:
null_vector = np.zeros(10)
print(null_vector)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4: Finding the memory size of any array (★☆☆)

In [68]:
array = np.zeros((10, 10))
print(array.size * array.itemsize) # This will give memory size in bytes


800


#### 5: Getting the documentation of the numpy add function from the command line

In [69]:
#python -c 
import numpy as np; help(np.add)


Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6: Creating a null vector of size 10 but the fifth value which is 1

In [70]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7: Create a vector with values ranging from 10 to 49

In [71]:
vector = np.arange(10, 50)
print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8: Reversing a vector (first element becomes last)

In [72]:
vector = np.arange(10)
reversed_vector = vector[::-1]
print(reversed_vector)


[9 8 7 6 5 4 3 2 1 0]


#### 9: Creating a 3x3 matrix with values ranging from 0 to 8

In [73]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10: Finding indices of non-zero elements from [1,2,0,0,4,0]

In [74]:
array = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(array)
print(indices)


(array([0, 1, 4], dtype=int32),)


#### 11: Creating a 3x3 identity matrix

In [75]:
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12: Creating a 3x3x3 array with random values

In [76]:
random_array = np.random.random((3, 3, 3))
print(random_array)


[[[0.68922659 0.95342116 0.363677  ]
  [0.56189928 0.4898904  0.22483388]
  [0.54457883 0.68759902 0.99662515]]

 [[0.65075097 0.99233671 0.28014493]
  [0.44531966 0.92959871 0.85157562]
  [0.72023582 0.554049   0.2171998 ]]

 [[0.47734642 0.14126989 0.47539346]
  [0.24999911 0.9270133  0.58674886]
  [0.04288601 0.8413092  0.79619339]]]


#### 13: Creating a 10x10 array with random values and find the minimum and maximum values

In [77]:
array = np.random.random((10, 10))
min_value = np.min(array)
max_value = np.max(array)
print("Minimum:", min_value)
print("Maximum:", max_value)


Minimum: 0.0036017098257546953
Maximum: 0.9753020808572093


#### 14: Creating a random vector of size 30 and find the mean value

In [78]:
vector = np.random.random(30)
mean_value = np.mean(vector)
print("Mean:", mean_value)


Mean: 0.5328100057203563


#### 15: Creating a 2d array with 1 on the border and 0 inside

In [79]:
array = np.ones((5, 5))
array[1:-1, 1:-1] = 0
print(array)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16: Adding a border (filled with 0's) around an existing array

In [80]:
array = np.ones((3, 3))
array_with_border = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print(array_with_border)


[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17: Result of the expression

In [81]:
print(0 * np.nan)        # nan
print(np.nan == np.nan)  # False
print(np.inf > np.nan)   # False
print(np.nan - np.nan)   # nan
print(np.nan in set([np.nan]))  # True
print(0.3 == 3 * 0.1)    # False


nan
False
False
nan
True
False


#### 18: Creating a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [82]:
matrix = np.diag(np.arange(1, 5), k=-1)
print(matrix)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19: Creating a 8x8 matrix and filling it with a checkerboard pattern

In [83]:
matrix = np.zeros((8, 8), dtype=int)
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1
print(matrix)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20: Finding the index (x,y,z) of the 100th element

In [84]:
index = np.unravel_index(100, (6, 7, 8))
print(index)


(1, 5, 4)


#### 21: Creating a checkerboard 8x8 matrix using the tile function

In [85]:
matrix = np.tile([[0, 1], [1, 0]], (4, 4))
print(matrix)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22: Normalizing a 5x5 random matrix

In [86]:
matrix = np.random.random((5, 5))
normalized_matrix = (matrix - np.mean(matrix)) / np.std(matrix)
print(normalized_matrix)


[[-1.4869166   1.34592712  0.47959722  0.79243561  0.8965954 ]
 [ 0.35383312 -1.41239946 -1.03998011  1.34956503  0.83346635]
 [-0.84725184  1.03318425  1.04067706 -1.11945451 -0.13633338]
 [ 0.69147096 -0.29892461 -0.54945395  0.33371298  1.36455311]
 [-1.60340189 -1.63357863 -0.13828581  0.68961934 -0.93865674]]


#### 23: Creating a custom dtype that describes a color as four unsigned bytes (RGBA)

In [87]:
color_dtype = np.dtype([('R', np.ubyte),
                        ('G', np.ubyte),
                        ('B', np.ubyte),
                        ('A', np.ubyte)])
print(color_dtype)


[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


#### 51: Creating a structured array representing a position (x,y) and a color (r,g,b)

In [88]:
structured_array = np.zeros(1, dtype=[('position', [('x', float), ('y', float)]),
                                      ('color', [('r', int), ('g', int), ('b', int)])])
print(structured_array)


[((0., 0.), (0, 0, 0))]


#### 52: Finding the point by point distances for a random vector with shape (100,2) 

In [89]:
coordinates = np.random.random((100, 2))
distances = np.sqrt(np.sum((coordinates[None, :] - coordinates[:, None])**2, axis=-1))
print(distances)


[[0.         0.60451621 0.64299249 ... 0.85377646 0.47846179 0.26793612]
 [0.60451621 0.         0.60961436 ... 0.27836413 0.95906053 0.34078385]
 [0.64299249 0.60961436 0.         ... 0.64423821 0.62481056 0.51718818]
 ...
 [0.85377646 0.27836413 0.64423821 ... 0.         1.13778943 0.58615286]
 [0.47846179 0.95906053 0.62481056 ... 1.13778943 0.         0.6447037 ]
 [0.26793612 0.34078385 0.51718818 ... 0.58615286 0.6447037  0.        ]]


#### 53: Converting a float (32 bits) array into an integer (32 bits)

In [90]:
float_array = np.random.rand(10).astype(np.float32)
integer_array = float_array.view(np.int32)
print(integer_array)


[1058991089 1058535918 1064803312 1064989155 1054815815 1015460568
 1053458519 1054190865 1039194868 1062659155]


#### 55: Finding the equivalent of enumerate for numpy arrays

In [91]:
array = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(array):
    print(index, value)


(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56: Generating a generic 2D Gaussian-like array

In [92]:
x, y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
d = np.sqrt(x*x + y*y)
sigma, mu = 1.0, 0.0
gaussian = np.exp(-( (d-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(gaussian)


[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57: How to randomly place p elements in a 2D array

In [93]:
p = 3
array = np.zeros((5,5))
np.put(array, np.random.choice(range(5*5), p, replace=False), 1)
print(array)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0.]]


#### 58: Subtracting the mean of each row of a matrix

In [94]:
matrix = np.random.rand(3, 3)
mean_subtracted_matrix = matrix - matrix.mean(axis=1, keepdims=True)
print(mean_subtracted_matrix)


[[-0.10525301  0.06067904  0.04457397]
 [-0.21180155 -0.0612437   0.27304525]
 [ 0.14126607 -0.2455849   0.10431883]]


#### 59: Sorting an array by the nth column

In [95]:
array = np.random.randint(0, 10, (3,3))
n = 1  # Sort by the second column
sorted_array = array[array[:, n].argsort()]
print(sorted_array)


[[5 1 5]
 [2 4 2]
 [5 9 3]]


#### 60: How to tell if a given 2D array has null columns

In [96]:
array = np.random.randint(0, 3, (3, 3))
has_null_columns = np.any(np.all(array == 0, axis=0))
print(has_null_columns)


False


#### 61: Finding the nearest value from a given value in an array

In [97]:
array = np.random.random(10)
value = 0.5
nearest_value = array[(np.abs(array - value)).argmin()]
print(nearest_value)


0.4596167978118373


#### 62: Considering two arrays with shape (1,3) and (3,1), computing their sum using an iterator

In [98]:
A = np.arange(3).reshape(1,3)
B = np.arange(3).reshape(3,1)
iterator = np.nditer([A,B,None])
for x,y,z in iterator: 
    z[...] = x + y
print(iterator.operands[2])


[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63: Creating an array class that has a name attribute

In [99]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="No Name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "No Name")

array = NamedArray(np.arange(10), "MyArray")
print(array.name)


MyArray


#### 64: Adding 1 to each element indexed by a second vector 

In [100]:
vector = np.ones(10)
indices = np.random.randint(0, len(vector), 20)
np.add.at(vector, indices, 1)
print(vector)


[3. 2. 4. 3. 3. 1. 4. 6. 1. 3.]


#### 65: How to accumulate elements of a vector (X) to an array (F) based on an index list (I)

In [101]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I, X)
print(F)


[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66: Considering a (w,h,3) image of (dtype=ubyte), and computing the number of unique colors

In [102]:
w, h = 16, 16
image = np.random.randint(0, 256, (w, h, 3)).astype(np.ubyte)
unique_colors = len(np.unique(image.reshape(-1, 3), axis=0))
print(unique_colors)


256


#### 67: Considering a four dimensions array, and getting sum over the last two axis at once

In [103]:
array = np.random.randint(0, 10, (3,3,3,3))
sum_last_two_axes = array.sum(axis=(-2,-1))
print(sum_last_two_axes)


[[42 36 45]
 [32 35 27]
 [40 48 52]]


#### 68. Computing means of subsets of D using a vector S of same size describing subset  indices 

In [104]:
D = np.random.uniform(0, 1, 100)
S = np.random.randint(0, 10, 100)
means = np.bincount(S, weights=D) / np.bincount(S)
print(means)


[0.47144542 0.32749905 0.6955419  0.52742516 0.62430058 0.32327525
 0.49963671 0.4277209  0.50856443 0.45765375]


#### 69: Getting the diagonal of a dot product 

In [105]:
A = np.random.randint(0, 10, (3,3))
B = np.random.randint(0, 10, (3,3))
diagonal_dot_product = np.diag(np.dot(A, B))
print(diagonal_dot_product)


[  6  48 114]


#### 70: Building a new vector with 3 consecutive zeros interleaved between each value

In [106]:
vector = np.array([1, 2, 3, 4, 5])
zeros = 3
new_vector = np.zeros(len(vector) + (len(vector)-1)*zeros)
new_vector[::zeros+1] = vector
print(new_vector)


[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71: mulitplying an array of dimension (5,5,3) by an array with dimensions (5,5)

In [107]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
C = A * B[:,:,None]
print(C)

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72: Swapping two rows of an array

In [108]:
array = np.arange(9).reshape(3,3)
array[[0,1]] = array[[1,0]]
print(array)


[[3 4 5]
 [0 1 2]
 [6 7 8]]


#### 73: Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles

In [109]:
triangles = np.random.randint(0, 100, (10, 3))
lines = np.roll(triangles.repeat(2, axis=1), -1, axis=1)
lines = lines.reshape(len(lines)*3, 2)
lines = np.sort(lines, axis=1)
unique_lines = np.unique(lines, axis=0)
print(unique_lines)

[[ 0 37]
 [ 0 43]
 [ 2 30]
 [ 2 32]
 [ 2 49]
 [ 2 59]
 [ 7 45]
 [ 7 59]
 [ 8  9]
 [ 8 12]
 [ 8 33]
 [ 8 50]
 [ 8 58]
 [ 8 78]
 [ 9 58]
 [12 78]
 [22 45]
 [22 66]
 [30 32]
 [33 50]
 [37 43]
 [41 52]
 [41 54]
 [45 59]
 [45 66]
 [47 89]
 [47 92]
 [49 59]
 [52 54]
 [89 92]]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? 

In [110]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)


[1 1 2 3 4 4 6]


#### 75: Computing averages using a sliding window over an array

In [111]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

array = np.array([1,2,3,4,5,6,7,8,9,10])
print(moving_average(array, n=3))

[2. 3. 4. 5. 6. 7. 8. 9.]


#### 76: Building a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) 

In [112]:
Z = np.arange(10)
n = 3
result = np.lib.stride_tricks.sliding_window_view(Z, (n,))
print(result)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77: How to negate a boolean, or to change the sign of a float inplace

In [113]:
array = np.random.randint(0,2,10)
np.logical_not(array, out=array)

float_array = np.random.uniform(-1.0, 1.0, 10)
np.negative(float_array, out=float_array)
print(array)
print(float_array)

[1 1 1 0 1 0 1 1 1 1]
[ 0.32978221  0.67395523  0.05839068  0.44564159 -0.95986273  0.89022698
 -0.02409098 -0.14591671 -0.3799088  -0.59685602]


#### 78: Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])

In [114]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10, 10, ( 1,2))

print(distance(P0, P1, p))

[ 3.65061992  5.80979922  4.9141998   6.26357085 10.20280601  4.94358083
  5.33248153  2.14633691  4.9252928   4.11227796]


#### 79: Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])

In [115]:
def distance(P0, P1, P):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-P[...,0])*T[:,0] + (P0[:,1]-P[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - P
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
P  = np.random.uniform(-10, 10, (10,2))

print(distance(P0, P1, P))

[ 2.32092486  0.29202597  4.7596188   0.59058092  6.82951591 13.21912039
  5.62307746  2.52985604  1.80042549 10.10805045]


#### 80: Function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary)

In [116]:
def extract_subpart(array, shape, position, fill=0):
    R, C = shape
    r, c = position
    r_off, c_off = (R - 1) // 2, (C - 1) // 2
    r_start, c_start = r - r_off, c - c_off
    r_end, c_end = r + r_off + 1, c + c_off + 1
    subpart = array[max(r_start, 0):r_end, max(c_start, 0):c_end]
    result = np.full(shape, fill, dtype=array.dtype)
    r_offset = max(-r_start, 0)
    c_offset = max(-c_start, 0)
    r_start = max(r_start, 0)
    c_start = max(c_start, 0)
    result[r_offset:r_offset + subpart.shape[0], c_offset:c_offset + subpart.shape[1]] = subpart
    return result

array = np.random.randint(0, 10, (10, 10))
shape = (3, 3)
position = (5, 5)
subpart = extract_subpart(array, shape, position, fill=0)
print(subpart)


[[0 6 1]
 [9 8 2]
 [8 8 5]]
