#### 1: Importing the numpy package under the name `np`

In [262]:
import numpy as np


#### 2: Printing the numpy version and the configuration (★☆☆)

In [263]:
print(np.__version__)
print(np.show_config())


1.26.2
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30153",
      "commands": "cl.exe"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.0",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30153",
      "commands": "cl.exe"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "mkl-sdl",
      "found": true,
      "version": "2023.1",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/user/miniconda3/Library/include",
      "lib directory": "C:/Users/user/miniconda3/Library/lib",
      "openblas configuration": "u

c:\Users\user\miniconda3\Lib\site-packages\numpy\__config__.py:149: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


#### 3: Creating a null vector of size 10 (★☆☆)

In [264]:
null_vector = np.zeros(10)
print(null_vector)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4: Finding the memory size of any array (★☆☆)

In [265]:
array = np.zeros((10, 10))
print(array.size * array.itemsize) # This will give memory size in bytes


800


#### 5: Getting the documentation of the numpy add function from the command line

In [266]:
#python -c 
import numpy as np; help(np.add)


Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6: Creating a null vector of size 10 but the fifth value which is 1

In [267]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7: Create a vector with values ranging from 10 to 49

In [268]:
vector = np.arange(10, 50)
print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8: Reversing a vector (first element becomes last)

In [269]:
vector = np.arange(10)
reversed_vector = vector[::-1]
print(reversed_vector)


[9 8 7 6 5 4 3 2 1 0]


#### 9: Creating a 3x3 matrix with values ranging from 0 to 8

In [270]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10: Finding indices of non-zero elements from [1,2,0,0,4,0]

In [271]:
array = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(array)
print(indices)


(array([0, 1, 4], dtype=int64),)


#### 11: Creating a 3x3 identity matrix

In [272]:
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12: Creating a 3x3x3 array with random values

In [273]:
random_array = np.random.random((3, 3, 3))
print(random_array)


[[[0.18830662 0.6555216  0.72687971]
  [0.06816588 0.07800422 0.6552319 ]
  [0.55516862 0.42205188 0.22236847]]

 [[0.59429823 0.94344599 0.88480333]
  [0.23994484 0.33448252 0.98903677]
  [0.68867091 0.34594632 0.21924752]]

 [[0.43702359 0.02281784 0.26990528]
  [0.6359524  0.07819435 0.30753138]
  [0.09264893 0.69237783 0.21760142]]]


#### 13: Creating a 10x10 array with random values and find the minimum and maximum values

In [274]:
array = np.random.random((10, 10))
min_value = np.min(array)
max_value = np.max(array)
print("Minimum:", min_value)
print("Maximum:", max_value)


Minimum: 0.02130465330823572
Maximum: 0.9919295314713787


#### 14: Creating a random vector of size 30 and find the mean value

In [275]:
vector = np.random.random(30)
mean_value = np.mean(vector)
print("Mean:", mean_value)


Mean: 0.504774811685754


#### 15: Creating a 2d array with 1 on the border and 0 inside

In [276]:
array = np.ones((5, 5))
array[1:-1, 1:-1] = 0
print(array)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16: Adding a border (filled with 0's) around an existing array

In [277]:
array = np.ones((3, 3))
array_with_border = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print(array_with_border)


[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17: Result of the expression

In [278]:
print(0 * np.nan)        # nan
print(np.nan == np.nan)  # False
print(np.inf > np.nan)   # False
print(np.nan - np.nan)   # nan
print(np.nan in set([np.nan]))  # True
print(0.3 == 3 * 0.1)    # False


nan
False
False
nan
True
False


#### 18: Creating a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [279]:
matrix = np.diag(np.arange(1, 5), k=-1)
print(matrix)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19: Creating a 8x8 matrix and filling it with a checkerboard pattern

In [280]:
matrix = np.zeros((8, 8), dtype=int)
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1
print(matrix)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20: Finding the index (x,y,z) of the 100th element

In [281]:
index = np.unravel_index(100, (6, 7, 8))
print(index)


(1, 5, 4)


#### 21: Creating a checkerboard 8x8 matrix using the tile function

In [282]:
matrix = np.tile([[0, 1], [1, 0]], (4, 4))
print(matrix)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22: Normalizing a 5x5 random matrix

In [283]:
matrix = np.random.random((5, 5))
normalized_matrix = (matrix - np.mean(matrix)) / np.std(matrix)
print(normalized_matrix)


[[ 1.15511618 -1.12140828  0.74367879  0.14655349 -1.22824055]
 [ 1.32166681 -0.56954181  1.19538835  0.02314005 -1.49497263]
 [ 0.23459182 -0.33835006  1.24183257 -0.3531314  -1.39262955]
 [ 0.76086487 -1.26036807  0.97620621  0.69444288 -1.43949707]
 [ 0.47657521  1.33864682 -0.64168329 -1.37418611  0.90530477]]


#### 23: Creating a custom dtype that describes a color as four unsigned bytes (RGBA)

In [284]:
color_dtype = np.dtype([('R', np.ubyte),
                        ('G', np.ubyte),
                        ('B', np.ubyte),
                        ('A', np.ubyte)])
print(color_dtype)


[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


### 24: Multiplying a 5x3 matrix by a 3x2 matrix (real matrix product) 

In [285]:

matrix1 = np.random.random((5, 3))
matrix2 = np.random.random((3, 2))

product = np.dot(matrix1, matrix2)

print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

print("\nMatrix Product:")
print(product)

Matrix 1:
[[0.72535804 0.85535865 0.85898885]
 [0.81520145 0.87913773 0.77208816]
 [0.94989075 0.3204214  0.95152493]
 [0.46493588 0.29379914 0.86664315]
 [0.71801218 0.68377089 0.3033788 ]]

Matrix 2:
[[0.74128839 0.65809048]
 [0.74293887 0.09495202]
 [0.73067445 0.09161702]]

Matrix Product:
[[1.80081988 0.63726725]
 [1.82159004 0.69068864]
 [1.63745145 0.7427146 ]
 [1.19616038 0.41326597]
 [1.2619252  0.56523707]]


### 25: Negating all elements (in a 1D array) which are between 3 and 8, in place.

In [286]:
arr = np.array([1, 5, 4, 9, 7, 2, 6, 3, 8])

# Find the indices of elements between 3 and 8
indices = np.where((arr >= 3) & (arr <= 8))

# Negate the elements at the found indices
arr[indices] = -arr[indices]

print(arr)

[ 1 -5 -4  9 -7  2 -6 -3 -8]


### 26: What is the output of the following script? 

In [287]:
print(sum(range(5),-1))

from numpy import *

print(sum(range(5),-1))

10
10


### 27: Finding the legal expression

In [288]:
"""Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z """

'Z**Z\n2 << Z >> 2\nZ <- Z\n1j*Z\nZ/1/1\nZ<Z>Z '

### 28: What are the result of the following expressions?

In [289]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\user\AppData\Local\Temp\ipykernel_2104\548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\user\AppData\Local\Temp\ipykernel_2104\548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
C:\Users\user\AppData\Local\Temp\ipykernel_2104\548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-2.14748365e+09])

### 29: How to round away from zero a float array 

In [290]:
arr = np.array([-1.5, 2.3, -4.7, 5.9, -0.1])

rounded_arr = np.ceil(np.abs(arr)) * np.copysign(1, arr)

print(rounded_arr)

[-2.  3. -5.  6. -1.]


### 30: How to find common values between two arrays

In [291]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])

common_values = np.intersect1d(array1, array2)

print(common_values)

[4 5]


#### 31: Ignoring all numpy warnings (not recommended)

In [292]:
import numpy as np
import warnings

# Ignore all NumPy warnings
warnings.filterwarnings('ignore', category=FutureWarning)

# Reset warnings to default behavior
warnings.resetwarnings()

### 32: Is the following expressions true? 

np.sqrt(-1) == np.emath.sqrt(-1)

### 33: How to get the dates of yesterday, today and tomorrow

In [293]:
from datetime import datetime, timedelta

# Get today's date
today = datetime.now().date()

# Get yesterday's date
yesterday = today - timedelta(days=1)

# Get tomorrow's date
tomorrow = today + timedelta(days=1)

# Print the dates
print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2024-02-21
Today: 2024-02-22
Tomorrow: 2024-02-23


### 34: Getting all the dates corresponding to the month of July 2016

In [294]:
from datetime import datetime, timedelta

def get_dates_in_month(year, month):
    start_date = datetime(year, month, 1).date()
    next_month = start_date.replace(day=28) + timedelta(days=4)  # Adding 4 days to go beyond end of month
    end_date = next_month - timedelta(days=next_month.day)

    dates_in_month = []
    current_date = start_date
    while current_date <= end_date:
        dates_in_month.append(current_date)
        current_date += timedelta(days=1)

    return dates_in_month

# Getting all the dates in July 2016
dates_july_2016 = get_dates_in_month(2016, 7)

# Printing the dates
for date in dates_july_2016:
    print(date)

2016-07-01
2016-07-02
2016-07-03
2016-07-04
2016-07-05
2016-07-06
2016-07-07
2016-07-08
2016-07-09
2016-07-10
2016-07-11
2016-07-12
2016-07-13
2016-07-14
2016-07-15
2016-07-16
2016-07-17
2016-07-18
2016-07-19
2016-07-20
2016-07-21
2016-07-22
2016-07-23
2016-07-24
2016-07-25
2016-07-26
2016-07-27
2016-07-28
2016-07-29
2016-07-30
2016-07-31


### 35: How to compute ((A+B)*(-A/2)) in place (without copy)

In [295]:
A = np.array([1, 2, 3], dtype=float)
B = np.array([4, 5, 6])

# Computing ((A+B)*(-A/2)) in place
np.add(A, B, out=A)
np.negative(A, out=A)
np.divide(A, 2, out=A)

# Printing the result
print(A)

[-2.5 -3.5 -4.5]


### 36: Extracting the integer part of a random array of positive numbers using four different methods 

In [296]:
# Generating a random array of positive numbers
arr = np.random.rand(5) * 10  # Adjust the size of the array as needed

# Method 1: Using np.floor()
int_part_1 = np.floor(arr)
print("Method 1 (np.floor()):", int_part_1)

# Method 2: Using np.trunc()
int_part_2 = np.trunc(arr)
print("Method 2 (np.trunc()):", int_part_2)

# Method 3: Using np.ceil() and subtraction
int_part_3 = arr - (arr % 1)
print("Method 3 (np.ceil() and subtraction):", int_part_3)

# Method 4: Using np.astype()
int_part_4 = arr.astype(int)
print("Method 4 (np.astype()):", int_part_4)


Method 1 (np.floor()): [2. 2. 0. 2. 6.]
Method 2 (np.trunc()): [2. 2. 0. 2. 6.]
Method 3 (np.ceil() and subtraction): [2. 2. 0. 2. 6.]
Method 4 (np.astype()): [2 2 0 2 6]


### 37: Creating a 5x5 matrix with row values ranging from 0 to 4 

In [297]:
# Create a 1-dimensional array ranging from 0 to 4
row_values = np.arange(5)

# Create a 5x5 matrix by broadcasting the row values
matrix = np.tile(row_values, (5, 1))

# Print the matrix
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### 38: A generator function that generates 10 integers and use it to build an array 

In [298]:
def integer_generator():
    for i in range(10):
        yield i

# Create an array using the generator function
array = np.fromiter(integer_generator(), dtype=int)

# Print the array
print(array)

[0 1 2 3 4 5 6 7 8 9]


### 39: Create a vector of size 10 with values ranging from 0 to 1, both excluded 

In [299]:
vector = np.linspace(0, 1, 10, endpoint=False)[1:]

# Printing the vector
print(vector)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


### 40: Create a random vector of size 10 and sort it (★★☆)

In [300]:
# Creating a random vector of size 10
vector = np.random.rand(10)

# Sorting the vector
sorted_vector = np.sort(vector)

# Printing the sorted vector
print(sorted_vector)


[0.19332582 0.25688499 0.28601334 0.28891915 0.39015381 0.40021487
 0.59036991 0.65817096 0.67233058 0.71761725]


### 41: How to sum a small array faster than np.sum

In [301]:
import math
arr = [1, 2, 3, 4, 5]
total = sum(arr)


arr = [1.1, 2.2, 3.3, 4.4, 5.5]
total = math.fsum(arr)


### 42: Checking if two random array A and B,  are equal

In [302]:
# Generate two random arrays A and B
A = np.random.rand(5)
B = np.random.rand(5)

# Check if A and B are equal
are_equal = np.array_equal(A, B)

# Print the result
print(are_equal)

False


### 43: Make an array immutable (read-only) 

In [303]:
mutable_array = np.array([1, 2, 3, 4, 5])

# Making the array immutable
immutable_array = mutable_array.copy()
immutable_array.flags.writeable = False

try:
    # Trying to modify the immutable array
    immutable_array[0] = 10  # This will raise a ValueError
except ValueError as e:
    print("Attempted modification of immutable array ignored.")



Attempted modification of immutable array ignored.


### 44: Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [304]:
# Creating a random 10x2 matrix representing Cartesian coordinates
cartesian_coords = np.random.rand(10, 2)

# Convert Cartesian coordinates to polar coordinates
x = cartesian_coords[:, 0]
y = cartesian_coords[:, 1]
r = np.hypot(x, y)
theta = np.arctan2(y, x)

# Stacking r and theta to form a 10x2 matrix representing polar coordinates
polar_coords = np.column_stack((r, theta))

# Printing the polar coordinates
print(polar_coords)

[[0.95236481 0.13324849]
 [0.99488601 0.00806542]
 [0.69044966 0.67966087]
 [1.08613436 1.1394707 ]
 [0.4792617  0.88684847]
 [0.40418802 0.01333778]
 [0.90579016 1.09626709]
 [1.09268197 0.51625965]
 [1.02933691 1.00954683]
 [0.8380978  1.49602818]]


### 45: Creating a random vector of size 10 and replacing the maximum value by 0 

In [305]:
# Creating a random vector of size 10
vector = np.random.rand(10)

# Finding the maximum value in the vector
max_value = np.max(vector)

# Replacing the maximum value with 0
vector[vector == max_value] = 0

# Printing the updated vector
print(vector)

[0.         0.15694857 0.07553608 0.51028909 0.20327651 0.81809342
 0.50993977 0.74338387 0.39105979 0.06039703]


### 46: Creating a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area 

In [306]:
# Defining the number of points in each dimension
num_points = 5

# Creating a grid of x and y coordinates
x_coords = np.linspace(0, 1, num_points)
y_coords = np.linspace(0, 1, num_points)
xx, yy = np.meshgrid(x_coords, y_coords)

# Creating a structured array
structured_array = np.zeros((num_points*num_points,), dtype=[('x', float), ('y', float)])
structured_array['x'] = xx.flatten()
structured_array['y'] = yy.flatten()

# Printing the structured array
print(structured_array)


[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )
 (0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)
 (0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )
 (0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)
 (0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]


### 47: Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [307]:
# Example arrays X and Y
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

# Computing the Cauchy matrix
C = 1 / (X[:, np.newaxis] - Y)

# Printing the Cauchy matrix
print(C)

[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


### 48: Printing the minimum and maximum representable value for each numpy scalar type 

In [308]:
# Integer scalar types
integer_types = [np.int8, np.int16, np.int32, np.int64,
                 np.uint8, np.uint16, np.uint32, np.uint64]

for int_type in integer_types:
    info = np.iinfo(int_type)
    print(f"{int_type.__name__}: min={info.min}, max={info.max}")

# Floating-point scalar types
float_types = [np.float16, np.float32, np.float64]

for float_type in float_types:
    info = np.finfo(float_type)
    print(f"{float_type.__name__}: min={info.min}, max={info.max}")

int8: min=-128, max=127
int16: min=-32768, max=32767
int32: min=-2147483648, max=2147483647
int64: min=-9223372036854775808, max=9223372036854775807
uint8: min=0, max=255
uint16: min=0, max=65535
uint32: min=0, max=4294967295
uint64: min=0, max=18446744073709551615
float16: min=-65504.0, max=65504.0
float32: min=-3.4028234663852886e+38, max=3.4028234663852886e+38
float64: min=-1.7976931348623157e+308, max=1.7976931348623157e+308


### 49: Printing all the values of an array

In [309]:
# Creating an example array
arr = np.array([1, 2, 3, 4, 5])

# Printing all the values of the array
print(arr)

[1 2 3 4 5]


### 50: Find the closest value (to a given scalar) in a vector

In [310]:
# Example vector
vector = np.array([1, 4, 7, 10])

# Target scalar
target = 6

# Find the index of the closest value
index = np.abs(vector - target).argmin()

# Get the closest value
closest_value = vector[index]

# Print the closest value
print(closest_value)

7


#### 51: Creating a structured array representing a position (x,y) and a color (r,g,b)

In [311]:
structured_array = np.zeros(1, dtype=[('position', [('x', float), ('y', float)]),
                                      ('color', [('r', int), ('g', int), ('b', int)])])
print(structured_array)


[((0., 0.), (0, 0, 0))]


#### 52: Finding the point by point distances for a random vector with shape (100,2) 

In [312]:
coordinates = np.random.random((100, 2))
distances = np.sqrt(np.sum((coordinates[None, :] - coordinates[:, None])**2, axis=-1))
print(distances)


[[0.         0.38926489 0.71370806 ... 0.96081331 0.3223847  0.78514282]
 [0.38926489 0.         0.32934086 ... 0.61689959 0.34333761 0.44795519]
 [0.71370806 0.32934086 0.         ... 0.33528569 0.6354355  0.36932274]
 ...
 [0.96081331 0.61689959 0.33528569 ... 0.         0.95136646 0.67051088]
 [0.3223847  0.34333761 0.6354355  ... 0.95136646 0.         0.55244754]
 [0.78514282 0.44795519 0.36932274 ... 0.67051088 0.55244754 0.        ]]


#### 53: Converting a float (32 bits) array into an integer (32 bits)

In [313]:
float_array = np.random.rand(10).astype(np.float32)
integer_array = float_array.view(np.int32)
print(integer_array)


[1063672638 1051297893 1057778687 1060565800 1062622304 1053990527
 1037914735 1061150667 1046099457 1061660658]


#### 55: Finding the equivalent of enumerate for numpy arrays

In [314]:
array = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(array):
    print(index, value)


(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56: Generating a generic 2D Gaussian-like array

In [315]:
x, y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
d = np.sqrt(x*x + y*y)
sigma, mu = 1.0, 0.0
gaussian = np.exp(-( (d-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(gaussian)


[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57: How to randomly place p elements in a 2D array

In [316]:
p = 3
array = np.zeros((5,5))
np.put(array, np.random.choice(range(5*5), p, replace=False), 1)
print(array)


[[1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 58: Subtracting the mean of each row of a matrix

In [317]:
matrix = np.random.rand(3, 3)
mean_subtracted_matrix = matrix - matrix.mean(axis=1, keepdims=True)
print(mean_subtracted_matrix)


[[-0.11455202 -0.00964929  0.12420132]
 [-0.10899378 -0.20600906  0.31500285]
 [ 0.29690196 -0.60586266  0.3089607 ]]


#### 59: Sorting an array by the nth column

In [318]:
array = np.random.randint(0, 10, (3,3))
n = 1  # Sort by the second column
sorted_array = array[array[:, n].argsort()]
print(sorted_array)


[[4 1 1]
 [8 1 1]
 [6 7 1]]


#### 60: How to tell if a given 2D array has null columns

In [319]:
array = np.random.randint(0, 3, (3, 3))
has_null_columns = np.any(np.all(array == 0, axis=0))
print(has_null_columns)


False


#### 61: Finding the nearest value from a given value in an array

In [320]:
array = np.random.random(10)
value = 0.5
nearest_value = array[(np.abs(array - value)).argmin()]
print(nearest_value)


0.5073788093503514


#### 62: Considering two arrays with shape (1,3) and (3,1), computing their sum using an iterator

In [321]:
A = np.arange(3).reshape(1,3)
B = np.arange(3).reshape(3,1)
iterator = np.nditer([A,B,None])
for x,y,z in iterator: 
    z[...] = x + y
print(iterator.operands[2])


[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63: Creating an array class that has a name attribute

In [322]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="No Name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "No Name")

array = NamedArray(np.arange(10), "MyArray")
print(array.name)


MyArray


#### 64: Adding 1 to each element indexed by a second vector 

In [323]:
vector = np.ones(10)
indices = np.random.randint(0, len(vector), 20)
np.add.at(vector, indices, 1)
print(vector)


[6. 5. 1. 3. 1. 3. 3. 3. 1. 4.]


#### 65: How to accumulate elements of a vector (X) to an array (F) based on an index list (I)

In [324]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I, X)
print(F)


[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66: Considering a (w,h,3) image of (dtype=ubyte), and computing the number of unique colors

In [325]:
w, h = 16, 16
image = np.random.randint(0, 256, (w, h, 3)).astype(np.ubyte)
unique_colors = len(np.unique(image.reshape(-1, 3), axis=0))
print(unique_colors)


256


#### 67: Considering a four dimensions array, and getting sum over the last two axis at once

In [326]:
array = np.random.randint(0, 10, (3,3,3,3))
sum_last_two_axes = array.sum(axis=(-2,-1))
print(sum_last_two_axes)


[[42 30 46]
 [42 46 32]
 [41 43 42]]


#### 68. Computing means of subsets of D using a vector S of same size describing subset  indices 

In [327]:
D = np.random.uniform(0, 1, 100)
S = np.random.randint(0, 10, 100)
means = np.bincount(S, weights=D) / np.bincount(S)
print(means)


[0.55056365 0.55811167 0.40182013 0.49928279 0.41615889 0.5143225
 0.50936079 0.3943793  0.47658876 0.5624778 ]


#### 69: Getting the diagonal of a dot product 

In [328]:
A = np.random.randint(0, 10, (3,3))
B = np.random.randint(0, 10, (3,3))
diagonal_dot_product = np.diag(np.dot(A, B))
print(diagonal_dot_product)


[33 93 22]


#### 70: Building a new vector with 3 consecutive zeros interleaved between each value

In [329]:
vector = np.array([1, 2, 3, 4, 5])
zeros = 3
new_vector = np.zeros(len(vector) + (len(vector)-1)*zeros)
new_vector[::zeros+1] = vector
print(new_vector)


[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71: mulitplying an array of dimension (5,5,3) by an array with dimensions (5,5)

In [330]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
C = A * B[:,:,None]
print(C)

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72: Swapping two rows of an array

In [331]:
array = np.arange(9).reshape(3,3)
array[[0,1]] = array[[1,0]]
print(array)


[[3 4 5]
 [0 1 2]
 [6 7 8]]


#### 73: Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles

In [332]:
triangles = np.random.randint(0, 100, (10, 3))
lines = np.roll(triangles.repeat(2, axis=1), -1, axis=1)
lines = lines.reshape(len(lines)*3, 2)
lines = np.sort(lines, axis=1)
unique_lines = np.unique(lines, axis=0)
print(unique_lines)

[[ 1 16]
 [ 1 83]
 [ 2 23]
 [ 2 69]
 [ 4 38]
 [ 4 90]
 [16 83]
 [17 63]
 [17 97]
 [20 52]
 [20 79]
 [21 30]
 [21 68]
 [23 69]
 [25 38]
 [25 57]
 [30 68]
 [38 57]
 [38 90]
 [40 51]
 [40 98]
 [43 58]
 [43 92]
 [51 98]
 [52 79]
 [58 92]
 [63 97]
 [67 72]
 [67 83]
 [72 83]]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? 

In [333]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)


[1 1 2 3 4 4 6]


#### 75: Computing averages using a sliding window over an array

In [334]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

array = np.array([1,2,3,4,5,6,7,8,9,10])
print(moving_average(array, n=3))

[2. 3. 4. 5. 6. 7. 8. 9.]


#### 76: Building a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) 

In [335]:
Z = np.arange(10)
n = 3
result = np.lib.stride_tricks.sliding_window_view(Z, (n,))
print(result)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77: How to negate a boolean, or to change the sign of a float inplace

In [336]:
array = np.random.randint(0,2,10)
np.logical_not(array, out=array)

float_array = np.random.uniform(-1.0, 1.0, 10)
np.negative(float_array, out=float_array)
print(array)
print(float_array)

[1 1 1 0 1 0 0 0 1 1]
[-0.51811393  0.2723329  -0.02739959 -0.28170368  0.92144975 -0.10014716
  0.75110924 -0.715918   -0.852206   -0.5005306 ]


#### 78: Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])

In [337]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10, 10, ( 1,2))

print(distance(P0, P1, p))

[ 1.07539905  5.44163716 12.34703459  7.01846127  5.70911505  1.01921282
  6.32496111 12.35739147  7.58529269  7.61033237]


#### 79: Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])

In [338]:
def distance(P0, P1, P):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-P[...,0])*T[:,0] + (P0[:,1]-P[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - P
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
P  = np.random.uniform(-10, 10, (10,2))

print(distance(P0, P1, P))

[ 4.3668773   9.3538279  12.20784696  3.95609822  6.99951029 14.78431454
  9.2231105  14.0034543   0.5721129   4.22082701]


#### 80: Function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary)

In [339]:
def extract_subpart(array, shape, position, fill=0):
    R, C = shape
    r, c = position
    r_off, c_off = (R - 1) // 2, (C - 1) // 2
    r_start, c_start = r - r_off, c - c_off
    r_end, c_end = r + r_off + 1, c + c_off + 1
    subpart = array[max(r_start, 0):r_end, max(c_start, 0):c_end]
    result = np.full(shape, fill, dtype=array.dtype)
    r_offset = max(-r_start, 0)
    c_offset = max(-c_start, 0)
    r_start = max(r_start, 0)
    c_start = max(c_start, 0)
    result[r_offset:r_offset + subpart.shape[0], c_offset:c_offset + subpart.shape[1]] = subpart
    return result

array = np.random.randint(0, 10, (10, 10))
shape = (3, 3)
position = (5, 5)
subpart = extract_subpart(array, shape, position, fill=0)
print(subpart)


[[0 1 2]
 [0 7 1]
 [3 1 5]]


### 81: Generating an array of R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]

In [340]:
Z = np.arange (1, 15)
window_size = 4
R = np.lib.stride_tricks.sliding_window_view(Z, (window_size,))

print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


### 82: Computing a Matrix rank

In [341]:
matrix = np.random.uniform(0, 1, (4, 4))
rank = np.linalg.matrix_rank(matrix)

print(rank)

4


### 83: Finding the most frequent value in an array

In [342]:
array = np.random.randint(0, 10, 20)

most_frequent_value = np.bincount(array).argmax()

print(most_frequent_value)

2


### 84: Extracting all the contiguous 3x3 blocks from a random 10x10 matrix

In [343]:
matrix = np.random.randint(0, 10, (10, 10))

blocks = np.lib.stride_tricks.sliding_window_view(matrix, (3, 3))

print(blocks)

[[[[0 3 5]
   [7 9 8]
   [2 4 6]]

  [[3 5 7]
   [9 8 0]
   [4 6 3]]

  [[5 7 7]
   [8 0 7]
   [6 3 7]]

  [[7 7 3]
   [0 7 3]
   [3 7 2]]

  [[7 3 9]
   [7 3 4]
   [7 2 4]]

  [[3 9 7]
   [3 4 9]
   [2 4 6]]

  [[9 7 4]
   [4 9 8]
   [4 6 1]]

  [[7 4 2]
   [9 8 9]
   [6 1 7]]]


 [[[7 9 8]
   [2 4 6]
   [4 4 2]]

  [[9 8 0]
   [4 6 3]
   [4 2 1]]

  [[8 0 7]
   [6 3 7]
   [2 1 2]]

  [[0 7 3]
   [3 7 2]
   [1 2 0]]

  [[7 3 4]
   [7 2 4]
   [2 0 3]]

  [[3 4 9]
   [2 4 6]
   [0 3 3]]

  [[4 9 8]
   [4 6 1]
   [3 3 6]]

  [[9 8 9]
   [6 1 7]
   [3 6 3]]]


 [[[2 4 6]
   [4 4 2]
   [6 5 2]]

  [[4 6 3]
   [4 2 1]
   [5 2 0]]

  [[6 3 7]
   [2 1 2]
   [2 0 7]]

  [[3 7 2]
   [1 2 0]
   [0 7 3]]

  [[7 2 4]
   [2 0 3]
   [7 3 0]]

  [[2 4 6]
   [0 3 3]
   [3 0 9]]

  [[4 6 1]
   [3 3 6]
   [0 9 5]]

  [[6 1 7]
   [3 6 3]
   [9 5 1]]]


 [[[4 4 2]
   [6 5 2]
   [4 4 0]]

  [[4 2 1]
   [5 2 0]
   [4 0 0]]

  [[2 1 2]
   [2 0 7]
   [0 0 5]]

  [[1 2 0]
   [0 7 3]
   [0 5 3]]

  [[2 0 3]
   

### 85: Creating a 2D array subclass such that Z[i,j] == Z[j,i]

In [344]:
import numpy as np

# Define a new class `SymmetricArray` that inherits from `np.ndarray`
class SymmetricArray(np.ndarray):
    # Override the __new__ method to properly initialize the array
    def __new__(cls, input_array):
        # Convert the input array to a numpy array and create a view of the class
        obj = np.asarray(input_array).view(cls)
        return obj

    # Override the __setitem__ method to set values in a symmetric manner
    def __setitem__(self, index, value):
        # Extract row and column indices from the index tuple
        i, j = index
        # Set the value at index (i, j)
        super().__setitem__((i, j), value)
        # Set the corresponding symmetric value at index (j, i)
        super().__setitem__((j, i), value)

    # Override the __getitem__ method to get values
    def __getitem__(self, index):
        # Extract row and column indices from the index tuple
        i, j = index
        # Return the value at index (i, j)
        return super().__getitem__((i, j))

# Create an instance of the SymmetricArray class initialized with zeros
Z = SymmetricArray(np.zeros((5, 5)))

# Set a value at index (0, 1) (which also sets the symmetric value at index (1, 0))
Z[0, 1] = 2

# Print the value at index (1, 0) (which is symmetrically set with the above operation)
print(Z[1, 0])


2.0


### 86: How to compute the sum of of the p matrix products at once (result has shape (n,1))

In [345]:
p = 5
n =3
matrices = np.random.rand(p, n, n)
vectors = np.random.rand(p, n, 1)
result = np.sum(matrices @ vectors, axis=0)

print(result)

[[3.25211714]
 [4.96841331]
 [4.22065699]]


### 87: How to get the block-sum (block size is 4x4)?

In [346]:
array = np.random.randint(1, 10, (16, 16))
block_size = 4
block_sum = np.add.reduceat(np.add.reduceat(array, np.arange(0, array.shape[0], block_size), axis=0),
                            np.arange(0, array.shape[1], block_size), axis=1)
print(block_sum)


[[100  78  63  82]
 [ 54  84  96  88]
 [ 94  79  74  76]
 [ 85  98  66  75]]


### 88: How to implement the Game of Life using numpy arrays

In [347]:
def iterate_life(board):
    neighbor_count = sum(np.roll(np.roll(board, i, 0), j, 1)
                         for i in (-1, 0, 1) for j in (-1, 0, 1)
                         if (i != 0 or j != 0))
    new_board = (neighbor_count == 3) | (board & neighbor_count == 2)
    return new_board.astype(int)

board = np.random.randint(0, 2, (10, 10))
for _ in range(10):
    board = iterate_life(board)
    print(board)


[[0 0 0 1 1 1 0 0 0 0]
 [0 0 1 0 0 0 1 0 0 0]
 [1 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 1 1 0 0 0 0 0 0 1]
 [0 0 0 1 1 1 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0 1 0]]
[[0 0 1 0 0 0 0 0 0 0]
 [0 1 0 1 1 1 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 0 0 0 0]
 [1 0 0 1 1 0 0 0 0 0]
 [1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0 0 0]]
[[0 0 0 0 0 1 0 0 0 0]
 [0 1 0 1 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 1]
 [0 0 0 1 0 0 0 0 0 1]
 [0 1 0 0 1 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 1 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [1 0 0 1 1 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0

C:\Users\user\AppData\Local\Temp\ipykernel_2104\2112032432.py:2: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  neighbor_count = sum(np.roll(np.roll(board, i, 0), j, 1)


### 89: How to get the n largest values of an array 

In [348]:
array = np.random.randint(0, 100, 10)
n_largest_values = np.sort(array)[-n:]
print(n_largest_values)


[83 97 99]


### 90: Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)

In [349]:
arrays = [np.array([1, 2, 3]), np.array([4, 5]), np.array([6, 7])]
cartesian_product = np.array(np.meshgrid(*arrays)).T.reshape(-1, len(arrays))
print(cartesian_product)


[[1 4 6]
 [1 5 6]
 [2 4 6]
 [2 5 6]
 [3 4 6]
 [3 5 6]
 [1 4 7]
 [1 5 7]
 [2 4 7]
 [2 5 7]
 [3 4 7]
 [3 5 7]]


### 91: How to create a record array from a regular array

In [350]:
array = np.array([("Alice", 25, 4.0), ("Bob", 30, 4.5)], dtype=[("name", 'U10'), ("age", int), ("score", float)])
print(array)


[('Alice', 25, 4. ) ('Bob', 30, 4.5)]


#### 92: Computing Z vector to the power of 3 using 3 different methods

In [351]:
Z = np.random.rand(1000000)
# Method 1:
print(np.power(Z, 3))
# Method 2:
print(Z ** 3)
# Method 3:
print(np.einsum('i,i,i->i', Z, Z, Z))


[0.18807541 0.86939214 0.3816707  ... 0.00700328 0.27879828 0.08775999]
[0.18807541 0.86939214 0.3816707  ... 0.00700328 0.27879828 0.08775999]
[0.18807541 0.86939214 0.3816707  ... 0.00700328 0.27879828 0.08775999]


### 93: How to find rows of A that contain elements of each row of B regardless of the order of the elements in B

In [352]:
# Consider two arrays A and B
A = np.random.randint(0, 10, (8, 3))
B = np.random.randint(0, 10, (2, 2))

# Check if any row of A contains all elements of each row of B
contains_all_elements = np.all(np.isin(A[:, :, None], B), axis=(1, 2))
rows_with_elements_of_B = A[contains_all_elements]

print(rows_with_elements_of_B)


[]


### 94: Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

In [353]:
# Consider a 10x3 matrix
matrix = np.random.randint(0, 5, (10, 3))

# Finding rows with unequal values
unequal_rows = matrix[~np.all(matrix[:, 1:] == matrix[:, :-1], axis=1)]

print(unequal_rows)


[[4 1 4]
 [2 0 3]
 [0 3 4]
 [4 3 1]
 [3 0 0]
 [2 0 0]
 [0 4 0]
 [2 2 0]
 [3 3 4]
 [1 0 1]]


### 95: Converting a vector of ints into a matrix binary representation

In [354]:
# Consider a vector of integers
vector = np.array([1, 2, 3, 4, 5])

# Converting each integer to its binary representation
binary_matrix = ((vector[:, None] & (1 << np.arange(32))) > 0).astype(int)

print(binary_matrix)


[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


### 96: Given a two dimensional array, how to extract unique rows

In [355]:
# Consider a two-dimensional array
array = np.random.randint(0, 5, (5, 3))

# Convert the array to a set of tuples and then back to an array to remove duplicates
unique_rows = np.unique(array, axis=0)

print(unique_rows)


[[1 4 2]
 [2 3 1]
 [3 1 3]
 [3 3 1]
 [4 3 1]]


### 97: Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

In [356]:
# Consider two vectors A and B
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# Equivalent of inner product
inner_product = np.einsum('i,i->', A, B)

# Equivalent of outer product
outer_product = np.einsum('i,j->ij', A, B)

# Equivalent of sum
sum_result = np.einsum('i->', A)

# Equivalent of element-wise multiplication
mul_result = np.einsum('i,i->i', A, B)

print("Inner product:", inner_product)
print("Outer product:", outer_product)
print("Sum:", sum_result)
print("Element-wise multiplication:", mul_result)


Inner product: 32
Outer product: [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Sum: 6
Element-wise multiplication: [ 4 10 18]


### 98: Considering a path described by two vectors (X,Y), how to sample it using equidistant samples

In [357]:
# Consider two vectors X and Y describing a path
X = np.array([0, 1, 3, 6, 10])
Y = np.array([0, 2, 4, 7, 11])

# Calculate the total length of the path
distance = np.sqrt(np.diff(X)**2 + np.diff(Y)**2).sum()

# Determine the number of equidistant samples
num_samples = 10
step = distance / (num_samples - 1)

# Interpolate the path to obtain equidistant samples
t = np.arange(0, distance, step)
X_samples = np.interp(t, np.cumsum(np.hstack([[0], np.diff(X)**2 + np.diff(Y)**2])), X)
Y_samples = np.interp(t, np.cumsum(np.hstack([[0], np.diff(X)**2 + np.diff(Y)**2])), Y)

print(X_samples, Y_samples)


[0.         0.33253311 0.66506622 0.99759934 1.41266556 1.82833195
 2.24399834 2.65966473 3.05022075] [0.         0.66506622 1.33013245 1.99519867 2.41266556 2.82833195
 3.24399834 3.65966473 4.05022075]


### 99: Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.

In [358]:
# Consider an integer n and a 2D array X
n = 5
X = np.array([[1, 2, 2], [0, 3, 2], [5, 0, 0], [1, 1, 3]])

# Select rows from X which sum to n and contain only integers
selected_rows = X[(X.sum(axis=1) == n) & np.all(X.astype(int) == X, axis=1)]

print(selected_rows)


[[1 2 2]
 [0 3 2]
 [5 0 0]
 [1 1 3]]


### 100: Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means)

In [359]:
# Consider a 1D array X
X = np.random.normal(0, 1, 1000)

# Number of bootstrap samples
N = 1000

# Resample the elements of X with replacement N times
bootstrap_samples = np.random.choice(X, size=(len(X), N), replace=True)

# Compute the mean of each sample
bootstrap_means = np.mean(bootstrap_samples, axis=0)

# Compute 95% confidence intervals
confidence_intervals = np.percentile(bootstrap_means, [2.5, 97.5])

print(confidence_intervals)


[-0.09570512  0.02830994]
